apiVersion: v1
kind: Service
metadata:
  name: yellowjobs-backend-service
spec:
  selector:
    app: yellowjobs-backend
  ports:
    - protocol: "TCP"
      port: 4000
      targetPort: 4000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yellowjobs-backend
spec:
  selector:
    matchLabels:
      app: yellowjobs-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: yellowjobs-backend
    spec:
      containers:
        - name: yellowjobs-backend
          image: docker.io/yellowjobs/yellowjobs-backend:latest
          env:
            - name: BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: twitter-bearer-token
                  key: BEARER_TOKEN
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-uri
                  key: MONGO_URI
          ports:
            - containerPort: 4000
              protocol: "TCP"
